
version: 2

models:
    - name: stg_orders
      description: "Orders details"
      columns:
          - name: order_id
            description: "This is unique order_id - primary key"
            tests:
                - unique
                - not_null
          - name: cust_id
          - name: totalprice
            tests:
            - dbt_utils.accepted_range:
               arguments:
                min_value: 0
                max_value: 1000000
          - name: order_date
            
            

    - name: stg_lineitem
      description: "Lineitem data"
      columns:
          - name: order_id
            description: "The combination of order_id and part_id is unique"
            tests:
                - not_null
          - name: part_id
            tests:
                - not_null
          - name: quantity
            tests:
             - dbt_utils.accepted_range:
                arguments:
                 min_value: 0
                 max_value: 100000
          - name: ship_date
            
    - name: mart_cust_orders
      description: "List of Order items per customer"
      columns:
          - name: order_id
            description: "The primary key is combination of order_id, part_id and cust_id"
            tests:
                - not_null
          - name: cust_id
            tests:
                - not_null
          - name: totalprice
          - name: quantity
          - name: part_id
            tests:
                - not_null
